[package]
name = "rust-sketchpad"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"    # any version at least 0.8.5 but below 9.0.0
ctrlc = "3.4.0"
chrono = "0.4.26"
